---
language: python
python: "3.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
script:
  - ansible-playbook tests/travis_test.yml -i tests/travis_inventory --syntax-check
